// Attraction data — single source of truth for both the Leaflet map and the
// SEO-crawlable HTML list. Coordinates are pixels on the source image
// (dummy_map.jpg, 1200 × 998). Leaflet's CRS.Simple uses [y, x].
export const MAP_W = 1200;
export const MAP_H = 998;

// Category metadata — labels for each supported locale.
// URL locale prefix: /{locale}/  e.g. /en/, /zh-TW/, /zh-CN/
export const CATEGORY_META = {
  automatives: { label: 'Automotive',  label_tc: '汽車',   label_sc: '汽车'   },
  sponsors:    { label: 'Sponsors',    label_tc: '贊助商', label_sc: '赞助商' },
  culinary:    { label: 'Culinary',    label_tc: '美食',   label_sc: '美食'   },
  services:    { label: 'Services',    label_tc: '服務',   label_sc: '服务'   },
};

export const attractions = [
  { id:  1, category: "services",    name: "Bonhams",                        x:  982, y: 428, icon: "",         avatar: "services" },
  { id: 12, category: "culinary",    name: "Mecum Auctions",                 x:  900, y: 600, icon: "",         avatar: "culinary" },
  { id: 13, category: "services",    name: "Barrett-Jackson",                x: 1050, y: 200, icon: "",         avatar: "services" },
  { id:  2, category: "automatives", name: "Audi",                           x:  834, y: 325, icon: "",         avatar: "automatives" },
  { id: 14, category: "sponsors",    name: "BMW",                            x:  200, y: 200, icon: "",         avatar: "sponsors" },
  { id: 15, category: "culinary",    name: "Mercedes-Benz",                  x:  400, y: 180, icon: "",         avatar: "culinary" },
  { id: 16, category: "services",    name: "Porsche",                        x:  600, y: 150, icon: "",         avatar: "services" },
  { id: 17, category: "automatives", name: "Ferrari",                        x:  750, y: 200, icon: "",         avatar: "automatives" },
  { id: 18, category: "sponsors",    name: "Lamborghini",                    x:  950, y: 150, icon: "",         avatar: "sponsors" },
  { id: 19, category: "culinary",    name: "McLaren",                        x: 1100, y: 100, icon: "",         avatar: "culinary" },
  { id: 20, category: "services",    name: "Bentley",                        x:  150, y: 450, icon: "",         avatar: "services" },
  { id: 21, category: "automatives", name: "Rolls-Royce",                    x:  300, y: 550, icon: "",         avatar: "automatives" },
  { id: 22, category: "sponsors",    name: "Bugatti",                        x:  150, y: 300, icon: "",         avatar: "sponsors" },
  { id: 26, category: "sponsors",    name: "Jaguar",                         x:  100, y: 600, icon: "",         avatar: "sponsors" },
  { id: 27, category: "culinary",    name: "Land Rover",                     x:  250, y: 680, icon: "",         avatar: "culinary" },
  { id: 28, category: "services",    name: "Maserati",                       x:  450, y: 720, icon: "",         avatar: "services" },
  { id: 29, category: "automatives", name: "Alfa Romeo",                     x:  650, y: 700, icon: "",         avatar: "automatives" },
  { id: 30, category: "sponsors",    name: "Lotus",                          x:  800, y: 720, icon: "",         avatar: "sponsors" },
  { id: 31, category: "culinary",    name: "Morgan",                         x:  950, y: 700, icon: "",         avatar: "culinary" },
  { id: 32, category: "services",    name: "AC Cars",                        x: 1100, y: 680, icon: "",         avatar: "services" },
  { id: 34, category: "sponsors",    name: "Volkswagen Group",               x:  350, y: 300, icon: "",         avatar: "sponsors" },
  { id:  3, category: "services",    name: "Custom Coachwork",               x:  363, y: 470, icon: "",         avatar: "services" },
  { id: 35, category: "automatives", name: "Pre-War Classics",               x:  120, y: 150, icon: "",         avatar: "automatives" },
  { id: 36, category: "sponsors",    name: "Post-War Sports",                x:  480, y: 350, icon: "",         avatar: "sponsors" },
  { id: 37, category: "culinary",    name: "Muscle Cars",                    x:  700, y: 450, icon: "",         avatar: "culinary" },
  { id: 38, category: "services",    name: "European Sports",                x:  820, y: 150, icon: "",         avatar: "services" },
  { id: 40, category: "sponsors",    name: "Racing Cars",                    x:  630, y: 580, icon: "",         avatar: "sponsors" },
  { id: 41, category: "culinary",    name: "Motorcycles",                    x:  200, y: 760, icon: "",         avatar: "culinary" },
  { id: 86, category: "services",    name: "Concours Judging Area",          x:  660, y: 310, icon: "",         avatar: "services" },
  { id:  4, category: "automatives", name: "Burgess",                        x:  229, y: 376, icon: "",         avatar: "automatives" },
  { id: 42, category: "sponsors",    name: "Northrop & Johnson",             x:  350, y: 150, icon: "",         avatar: "sponsors" },
  { id: 43, category: "culinary",    name: "Fraser Yachts",                  x:  500, y: 220, icon: "",         avatar: "culinary" },
  { id: 44, category: "services",    name: "Camper & Nicholsons",            x:  100, y: 350, icon: "",         avatar: "services" },
  { id: 45, category: "automatives", name: "VistaJet",                       x: 1050, y: 780, icon: "",         avatar: "automatives" },
  { id:  5, category: "services",    name: "Bangkok Pavilion",               x:  538, y: 513, icon: "",         avatar: "services" },
  { id: 48, category: "automatives", name: "The Lodge Restaurant",           x:  450, y: 430, icon: "",         avatar: "automatives" },
  { id: 49, category: "sponsors",    name: "Pacific's Edge",                 x:  680, y: 580, icon: "",         avatar: "sponsors" },
  { id: 50, category: "culinary",    name: "Pebble Beach Market",            x:  580, y: 680, icon: "",         avatar: "culinary" },
  { id: 51, category: "services",    name: "Stillwater Bar & Grill",         x:  750, y: 350, icon: "",         avatar: "services" },
  { id: 52, category: "automatives", name: "Roy's Restaurant",               x:  880, y: 460, icon: "",         avatar: "automatives" },
  { id: 53, category: "sponsors",    name: "The Tap Room",                   x:  320, y: 430, icon: "",         avatar: "sponsors" },
  { id: 54, category: "culinary",    name: "Traps",                          x:  760, y: 600, icon: "",         avatar: "culinary" },
  { id: 55, category: "services",    name: "Coffee Bar",                     x:  200, y: 500, icon: "lounge",   avatar: "services" },
  { id:  6, category: "automatives", name: "ArtCenter College of Design",    x:  699, y: 316, icon: "",         avatar: "automatives" },
  { id: 56, category: "sponsors",    name: "Petersen Museum Display",        x:  500, y: 120, icon: "",         avatar: "sponsors" },
  { id: 57, category: "culinary",    name: "Ralph Lauren Collection",        x:  130, y: 720, icon: "",         avatar: "culinary" },
  { id: 59, category: "automatives", name: "Concept Car Exhibition",         x:  900, y: 250, icon: "",         avatar: "automatives" },
  { id: 60, category: "sponsors",    name: "Classic Poster Gallery",         x:  680, y: 260, icon: "",         avatar: "sponsors" },
  { id:  7, category: "services",    name: "First Aid",                      x:  578, y: 402, icon: "firstAid", avatar: "services" },
  { id: 61, category: "services",    name: "Information Booth",              x:  660, y: 430, icon: "guest",    avatar: "services" },
  { id: 62, category: "automatives", name: "Lost & Found",                   x:  430, y: 570, icon: "",         avatar: "automatives" },
  { id: 63, category: "sponsors",    name: "ATM Services",                   x:  780, y: 490, icon: "",         avatar: "sponsors" },
  { id: 64, category: "culinary",    name: "Bag Check",                      x:  530, y: 300, icon: "",         avatar: "culinary" },
  { id: 66, category: "automatives", name: "Press Center",                   x:  350, y: 680, icon: "",         avatar: "automatives" },
  { id: 67, category: "sponsors",    name: "Volunteers HQ",                  x:  920, y: 380, icon: "",         avatar: "sponsors" },
  { id: 69, category: "services",    name: "Restrooms A",                    x:  430, y: 240, icon: "toilet",   avatar: "services" },
  { id: 70, category: "automatives", name: "Restrooms B",                    x:  850, y: 640, icon: "",         avatar: "automatives" },
  { id: 87, category: "services",    name: "Main Stage",                     x:  540, y: 450, icon: "stage",    avatar: "services" },
  { id: 88, category: "culinary",    name: "Kids Zone",                      x:  900, y: 760, icon: "",         avatar: "culinary" },
  { id: 89, category: "services",    name: "Merchandise Store",              x:  270, y: 580, icon: "",         avatar: "services" },
  { id:  8, category: "sponsors",    name: "Hagerty",                        x:  874, y: 539, icon: "",         avatar: "sponsors" },
  { id: 71, category: "culinary",    name: "Chubb Insurance",                x:  300, y: 350, icon: "",         avatar: "culinary" },
  { id: 73, category: "automatives", name: "Allianz",                        x:  600, y: 400, icon: "",         avatar: "automatives" },
  { id:  9, category: "services",    name: "To Bonhams Quail Lodge Auction", x:  443, y: 616, icon: "shuttle",  avatar: "services" },
  { id: 74, category: "culinary",    name: "To Pebble Beach Lodge",          x:  120, y: 540, icon: "",         avatar: "culinary" },
  { id: 76, category: "automatives", name: "To Monterey Airport",            x:  680, y: 760, icon: "",         avatar: "automatives" },
  { id: 78, category: "culinary",    name: "Michelin",                       x:  200, y: 260, icon: "",         avatar: "culinary" },
  { id: 80, category: "automatives", name: "Mobil 1",                        x:  380, y: 760, icon: "",         avatar: "automatives" },
  { id: 81, category: "sponsors",    name: "Pirelli",                        x:  770, y: 160, icon: "",         avatar: "sponsors" },
  { id: 83, category: "services",    name: "Bosch",                          x:  480, y: 650, icon: "shop",     avatar: "services" },
  { id: 84, category: "automatives", name: "Continental",                    x:  630, y: 180, icon: "",         avatar: "automatives" },
];